version: '3.8'

services:
  database:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:latest
    container_name: database
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 8081:3306
    # If you want to add credentials through env file
    #env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress-project-name
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=thepasstoruleoverdb
    expose:
      - 3306
      - 33060
    networks:
      - app-network

  wordpress:
    depends_on: # Won't start before db
      - database
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
    restart: unless-stopped
    # ports:
    #   - 8082:8082
    # If you want to add credentials through env file
    #env_file: .env
    environment:
      - WORDPRESS_DB_HOST=database # Should be the name of the database service
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=thepasstoruleoverdb
      - WORDPRESS_DB_NAME=wordpress-project-name
    networks:
      - app-network

  nginx-proxy:
    depends_on:
      wordpress:
        condition: service_started
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      # - wordpress:/var/www/html
      # - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx-conf/certs:/etc/nginx/certs
    networks:
      - app-network

volumes:
  database:
  wordpress:
  certbot-cert:
      external: true

networks:
  app-network:
    driver: bridge # Connects the services