version: "3"

services:
  database:
    container_name: database
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:latest
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    # If you want to add credentials through env file
    #env_file: .env
    environment:
      MYSQL_DATABASE: wordpress-project-name
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: thepasstoruleoverdb
    expose:
      - 3306
      - 33060
    networks:
      - wordpress-network

  # Optional admin panel
  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #   environment:
  #     - PMA_ARBITRARY=1

  wordpress:
    depends_on:
      - database
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    restart: unless-stopped
    # If you want to add credentials through env file
    #env_file: .env
    environment:
      WORDPRESS_DB_HOST: database # Should be the name of the database service
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: thepasstoruleoverdb
      WORDPRESS_DB_NAME: wordpress-project-name
    networks:
      - wordpress-network

  nginx:
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_started
    image: nginx:latest
    volumes:
      - ./wordpress/html:/var/www/html
      - ./nginx-config:/etc/nginx/conf.d
      - ./nginx-config/certs:/etc/nginx/ssl
    restart: unless-stopped
    ports:
      - 80:80   # Http
      - 443:443 # Https
    networks:
      - wordpress-network

volumes:
  database:
  wordpress:
  nginx:

networks:
  wordpress-network:
    driver: bridge # Connects the services